/**
 * Report Configuration panel
 */

import { HardwareModule } from "../ui/HardwareModule";
import { theme } from "../../utils/theme";

const REPORT_TYPES = [
  { key: "snapshot", label: "Current System Snapshot" },
  { key: "1h", label: "Last 1 Hour" },
  { key: "6h", label: "Last 6 Hours" },
  { key: "24h", label: "Last 24 Hours" },
  { key: "7d", label: "Last 7 Days" },
  { key: "30d", label: "Last 30 Days" },
  { key: "custom", label: "Custom Time Range" },
];

const inputClass =
  "w-full rounded-lg border px-3 py-2.5 text-sm text-[#f1f5f9] outline-none transition focus:ring-1 focus:ring-cyan-500/40";

const inputStyle = {
  background: "rgba(8, 12, 18, 0.8)",
  borderColor: "rgba(34, 211, 238, 0.15)",
  fontFamily: "JetBrains Mono, monospace",
};

export function ReportConfiguration({ config, updateConfig, sampleCount, connected, compact }) {
  const isCustom = config.intervalKey === "custom";

  return (
    <HardwareModule
      icon="diagnostics"
      title="Report Configuration"
      subtitle={compact ? undefined : "Define scope and metadata before generation"}
      accentColor={theme.cyan}
    >
      <div className={`grid gap-4 ${compact ? "grid-cols-1" : "lg:grid-cols-2"}`}>
        <label className={`flex flex-col gap-1.5 ${compact ? "" : "lg:col-span-2"}`}>
          <span className="text-[10px] font-semibold uppercase tracking-wider text-[#64748b]">
            Report Type
          </span>
          <select
            value={config.intervalKey}
            onChange={(e) => updateConfig({ intervalKey: e.target.value })}
            className={inputClass}
            style={inputStyle}
          >
            {REPORT_TYPES.map(({ key, label }) => (
              <option key={key} value={key} style={{ background: "#0a0e14" }}>
                {label}
              </option>
            ))}
          </select>
        </label>

        {isCustom && (
          <>
            <label className="flex flex-col gap-1.5">
              <span className="text-[10px] font-semibold uppercase tracking-wider text-[#64748b]">
                Start
              </span>
              <input
                type="datetime-local"
                className={inputClass}
                style={inputStyle}
                onChange={(e) => {
                  const start = e.target.value ? new Date(e.target.value).getTime() : null;
                  updateConfig({
                    customRange: { ...config.customRange, start },
                  });
                }}
              />
            </label>
            <label className="flex flex-col gap-1.5">
              <span className="text-[10px] font-semibold uppercase tracking-wider text-[#64748b]">
                End
              </span>
              <input
                type="datetime-local"
                className={inputClass}
                style={inputStyle}
                onChange={(e) => {
                  const end = e.target.value ? new Date(e.target.value).getTime() : null;
                  updateConfig({
                    customRange: { ...config.customRange, end },
                  });
                }}
              />
            </label>
          </>
        )}

        <label className="flex flex-col gap-1.5">
          <span className="text-[10px] font-semibold uppercase tracking-wider text-[#64748b]">
            Report Title <span className="font-normal normal-case text-[#475569]">(optional)</span>
          </span>
          <input
            type="text"
            placeholder="Hardware Monitoring Report"
            value={config.title}
            onChange={(e) => updateConfig({ title: e.target.value })}
            className={inputClass}
            style={inputStyle}
          />
        </label>

        <label className="flex flex-col gap-1.5">
          <span className="text-[10px] font-semibold uppercase tracking-wider text-[#64748b]">
            Generated By <span className="font-normal normal-case text-[#475569]">(optional)</span>
          </span>
          <input
            type="text"
            placeholder="Admin"
            value={config.generatedBy}
            onChange={(e) => updateConfig({ generatedBy: e.target.value })}
            className={inputClass}
            style={inputStyle}
          />
        </label>

        <label className={`flex flex-col gap-1.5 ${compact ? "" : "lg:col-span-2"}`}>
          <span className="text-[10px] font-semibold uppercase tracking-wider text-[#64748b]">
            Report Description <span className="font-normal normal-case text-[#475569]">(optional)</span>
          </span>
          <textarea
            rows={2}
            placeholder="Brief context for this report…"
            value={config.description}
            onChange={(e) => updateConfig({ description: e.target.value })}
            className={`${inputClass} resize-none`}
            style={inputStyle}
          />
        </label>
      </div>

      <p className="mt-3 font-mono-metrics text-xs text-[#64748b]">
        {sampleCount > 0
          ? `${sampleCount} historical sample${sampleCount === 1 ? "" : "s"} loaded from SQLite for this period.`
          : "Historical samples are loaded from the monitoring server database (not browser session)."}
        {!connected && " · Live telemetry offline — historical reports still use SQLite when the API is reachable."}
      </p>
    </HardwareModule>
  );
}
