/**
 * DOCX report export handler.
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
} from "docx";

function sanitizeFilename(name) {
  return (name || "Hardware_Monitoring_Report").replace(/[^\w-]+/g, "_").slice(0, 60);
}

function sectionEnabled(reportData, id) {
  if (!reportData.activeSections) return true;
  return reportData.activeSections[id] === true;
}

function heading(text, level = HeadingLevel.HEADING_1) {
  return new Paragraph({ text, heading: level, spacing: { after: 200 } });
}

function body(text) {
  return new Paragraph({ children: [new TextRun(text)], spacing: { after: 120 } });
}

function metricsTable(rows) {
  if (!rows?.length) return [];
  return [
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({
          children: ["Metric", "Avg", "Min", "Max", "Current", "Trend"].map(
            (h) =>
              new TableCell({
                children: [new Paragraph({ children: [new TextRun({ text: h, bold: true })] })],
              })
          ),
        }),
        ...rows.map(
          (row) =>
            new TableRow({
              children: row.map(
                (cell) =>
                  new TableCell({
                    children: [new Paragraph(String(cell ?? "—"))],
                  })
              ),
            })
        ),
      ],
    }),
    new Paragraph({ text: "", spacing: { after: 200 } }),
  ];
}

export async function exportReportDocx(reportData) {
  const children = [];

  children.push(
    heading(reportData.title || "Hardware Monitoring Report"),
    body(`Generated: ${reportData.generatedAt?.toLocaleString?.() || "—"}`),
    body(`Generated By: ${reportData.generatedBy || "—"}`),
    body(`Report Interval: ${reportData.intervalLabel}`),
    body(`Hostname: ${reportData.executive?.hostname || "—"}`)
  );

  if (reportData.description) {
    children.push(body(reportData.description));
  }

  if (sectionEnabled(reportData, "executiveSummary") && reportData.executive) {
    children.push(heading("Executive Summary", HeadingLevel.HEADING_2));
    children.push(body(`Overall Health: ${reportData.executive.overallHealth}`));
    children.push(body(`Health Score: ${reportData.executive.healthScore}`));
    children.push(body(reportData.executive.summary));
  }

  if (sectionEnabled(reportData, "systemInventory") && reportData.inventory) {
    children.push(heading("System Inventory", HeadingLevel.HEADING_2));
    const inv = reportData.inventory;
    children.push(body(`CPU: ${inv.cpu?.model || "—"}`));
    children.push(body(`Memory: ${inv.memory?.dimm_count ?? "—"} DIMM(s)`));
    children.push(body(`Storage: ${(inv.disks || []).length} device(s)`));
    children.push(body(`GPU: ${(inv.gpus || []).map((g) => g.model).join(", ") || "—"}`));
  }

  if (sectionEnabled(reportData, "hardwareHealthOverview") && reportData.componentHealthSnapshot?.length) {
    children.push(heading("Hardware Health Overview", HeadingLevel.HEADING_2));
    reportData.componentHealthSnapshot.forEach((c) => {
      children.push(body(`${c.name}: ${c.level}`));
    });
  }

  if (sectionEnabled(reportData, "cpuAnalysis") || sectionEnabled(reportData, "gpuAnalysis")) {
    (reportData.componentAnalysis || []).forEach((comp) => {
      const sectionMap = {
        CPU: "cpuAnalysis",
        GPU: "gpuAnalysis",
        RAM: "memoryAnalysis",
        DISK: "storageAnalysis",
        NIC: "networkAnalysis",
      };
      const sectionId = sectionMap[comp.name];
      if (!sectionId || !sectionEnabled(reportData, sectionId)) return;
      if (!comp.liveMetrics?.length && !comp.inventory?.length) return;
      children.push(heading(`${comp.name} Analysis`, HeadingLevel.HEADING_2));
      children.push(body(`Status: ${comp.status}`));
      comp.liveMetrics.forEach(([k, v]) => children.push(body(`${k}: ${v}`)));
    });
  }

  if (sectionEnabled(reportData, "connectivityStatus") && reportData.connectivityStatus) {
    children.push(heading("Connectivity Status", HeadingLevel.HEADING_2));
    children.push(
      body(`Link Health: ${reportData.connectivityStatus.linkHealth?.overall || "—"}`)
    );
    children.push(body(`Score: ${reportData.connectivityStatus.linkHealth?.score ?? "—"}`));
  }

  if (sectionEnabled(reportData, "activeFaults") && reportData.faultAnalysis?.length) {
    children.push(heading("Fault Analysis", HeadingLevel.HEADING_2));
    reportData.faultAnalysis.forEach((f) => {
      children.push(
        body(`[${f.severity}] ${f.component}${f.metricName ? ` — ${f.metricName}` : ""}`)
      );
      children.push(body(f.explanation));
    });
  }

  if (sectionEnabled(reportData, "recoveryHistory") && reportData.recoveryHistory?.length) {
    children.push(heading("Autonomous Recovery History", HeadingLevel.HEADING_2));
    reportData.recoveryHistory.forEach((r) => {
      children.push(
        body(`${r.component}: ${r.result} — ${r.verificationOutcome || r.reason || ""}`)
      );
    });
  }

  if (sectionEnabled(reportData, "aiRootCause") && reportData.aiRootCause?.length) {
    children.push(heading("AI Root Cause Analysis", HeadingLevel.HEADING_2));
    reportData.aiRootCause.forEach((item) => {
      children.push(body(`[${item.component}] ${item.analysis}`));
    });
  }

  if (sectionEnabled(reportData, "recommendations") && reportData.recommendations?.length) {
    children.push(heading("Recommendations", HeadingLevel.HEADING_2));
    reportData.recommendations.forEach((rec, i) => children.push(body(`${i + 1}. ${rec}`)));
  }

  if (sectionEnabled(reportData, "historicalTrends") && reportData.hardwareMetrics?.length) {
    children.push(heading("Hardware Metrics Summary", HeadingLevel.HEADING_2));
    children.push(...metricsTable(reportData.hardwareMetrics));
  }

  if (sectionEnabled(reportData, "rawTelemetry") && reportData.sampleCount > 0) {
    children.push(heading("Appendix — Telemetry Metadata", HeadingLevel.HEADING_2));
    children.push(body(`Samples in interval: ${reportData.sampleCount}`));
    children.push(body(`Monitoring span: ${reportData.span?.label || "—"}`));
  }

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  const buffer = await Packer.toBlob(doc);
  const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const filename = `${sanitizeFilename(reportData.title)}_${stamp}.docx`;
  return {
    blob: buffer,
    filename,
    pageCount: null,
    sizeBytes: buffer.size,
    format: "docx",
  };
}
