/**
 * PDF report export handler — enterprise document layout with section filtering.
 */

import { jsPDF } from "jspdf";

const NAVY = [0, 0, 128];
const BLUE = [77, 159, 255];
const GRAY = [109, 129, 150];
const WHITE = [255, 255, 255];
const DARK = [15, 30, 69];
const GREEN = [0, 200, 83];
const ORANGE = [255, 152, 0];
const RED = [183, 28, 28];

function sectionOn(reportData, id) {
  if (!reportData.activeSections) return true;
  return reportData.activeSections[id] === true;
}

function levelColor(level) {
  if (level === "critical") return RED;
  if (level === "warning") return ORANGE;
  if (level === "healthy") return GREEN;
  return GRAY;
}

function statusLabel(level) {
  if (level === "critical") return "Critical";
  if (level === "warning") return "Warning";
  if (level === "healthy") return "Healthy";
  return "Unknown";
}

function drawLineChart(doc, points, x, y, w, h, color = BLUE) {
  if (points.length < 2) return;
  const values = points.map((p) => p.v);
  const min = Math.min(...values);
  const max = Math.max(...values);
  const range = max - min || 1;

  doc.setDrawColor(220, 228, 240);
  doc.setLineWidth(0.2);
  doc.rect(x, y, w, h);

  for (let i = 0; i <= 4; i += 1) {
    const gy = y + (h / 4) * i;
    doc.line(x, gy, x + w, gy);
  }

  doc.setDrawColor(...color);
  doc.setLineWidth(0.6);
  const step = w / (points.length - 1);
  for (let i = 0; i < points.length - 1; i += 1) {
    const x1 = x + i * step;
    const x2 = x + (i + 1) * step;
    const y1 = y + h - ((values[i] - min) / range) * (h - 4) - 2;
    const y2 = y + h - ((values[i + 1] - min) / range) * (h - 4) - 2;
    doc.line(x1, y1, x2, y2);
  }

  doc.setFontSize(7);
  doc.setTextColor(...GRAY);
  doc.text(`${min}`, x + 2, y + h + 4);
  doc.text(`${max}`, x + w - 12, y + h + 4);
}

function drawBarChart(doc, items, x, y, w, h) {
  if (!items.length) return;
  const maxVal = Math.max(...items.map((i) => i.value), 1);
  const barW = Math.min(w / items.length - 2, 24);
  const gap = (w - barW * items.length) / (items.length + 1);

  doc.setDrawColor(220, 228, 240);
  doc.rect(x, y, w, h);

  items.forEach((item, i) => {
    const barH = (item.value / maxVal) * (h - 8);
    const bx = x + gap + i * (barW + gap);
    const by = y + h - barH - 2;
    doc.setFillColor(...(item.color || BLUE));
    doc.rect(bx, by, barW, barH, "F");
    doc.setFontSize(6);
    doc.setTextColor(40, 40, 40);
    doc.text(String(item.value), bx + barW / 2, by - 1, { align: "center" });
    doc.setTextColor(...GRAY);
    const label = doc.splitTextToSize(item.label, barW + 4);
    doc.text(label, bx + barW / 2, y + h + 4, { align: "center" });
  });
}

function drawHorizontalHealthBar(doc, components, x, y, w) {
  const barH = 6;
  const gap = 3;
  components.forEach((c, i) => {
    const cy = y + i * (barH + gap);
    doc.setFontSize(8);
    doc.setTextColor(40, 40, 40);
    doc.text(c.name, x, cy + 4);
    const bx = x + 28;
    const bw = w - 28;
    doc.setFillColor(230, 235, 245);
    doc.rect(bx, cy, bw, barH, "F");
    doc.setFillColor(...levelColor(c.level));
    doc.rect(bx, cy, bw, barH, "F");
    doc.setFontSize(7);
    doc.setTextColor(...WHITE);
    doc.text(statusLabel(c.level), bx + 2, cy + 4);
  });
  return y + components.length * (barH + gap);
}

function addPageHeader(doc, title) {
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, 210, 18, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 12);
  doc.setFont("helvetica", "normal");
}

function ensureSpace(doc, y, needed, title) {
  if (y + needed > 280) {
    doc.addPage();
    addPageHeader(doc, title);
    return 28;
  }
  return y;
}

function sanitizeFilename(name) {
  return (name || "Hardware_Monitoring_Report").replace(/[^\w-]+/g, "_").slice(0, 60);
}

export function exportReportPdf(reportData) {
  const docTitle = reportData.title || "Hardware Monitoring Report";
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = 0;

  doc.setFillColor(...NAVY);
  doc.rect(0, 0, 210, 297, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(26);
  doc.setFont("helvetica", "bold");
  doc.text(docTitle, 105, 65, { align: "center" });
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...BLUE);
  doc.text("Framework Block Ledger — Hardware Monitoring", 105, 78, { align: "center" });
  doc.setTextColor(200, 220, 255);
  doc.setFontSize(10);
  const coverLines = [
    ["Report Generated", reportData.generatedAt.toLocaleString()],
    ["Generated By", reportData.generatedBy || "—"],
    ["Report ID", `HMR-${reportData.generatedAt.getTime().toString(36).toUpperCase()}`],
    ["Hostname", reportData.executive.hostname],
    ["Operating System", reportData.executive.os],
    ["Report Interval", reportData.intervalLabel],
    ["Monitoring Span", reportData.executive.monitoringDuration],
    ["Samples Collected", String(reportData.sampleCount)],
    ["Data Source", "Live Hardware Monitor Telemetry"],
  ];
  if (reportData.description) coverLines.splice(2, 0, ["Description", reportData.description]);
  y = 92;
  coverLines.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, 35, y);
    doc.setFont("helvetica", "normal");
    doc.text(String(value ?? "Not Available"), 90, y);
    y += 9;
  });

  if (sectionOn(reportData, "executiveSummary")) {
    doc.addPage();
    addPageHeader(doc, docTitle);
    y = 28;
    doc.setTextColor(...NAVY);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Executive Summary", 14, y);
    y += 10;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);

    const execRows = [
      ["Overall System Health", reportData.executive.overallHealth],
      ["Health Score", reportData.executive.healthScore],
      ["Monitoring Duration", reportData.executive.monitoringDuration],
      ["Active Critical Conditions", String(reportData.executive.criticalAlerts)],
      ["Active Warning Conditions", String(reportData.executive.warningAlerts)],
      ["Total Fault Events (interval)", String(reportData.faults.length)],
    ];
    execRows.forEach(([k, v]) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${k}:`, 14, y);
      doc.setFont("helvetica", "normal");
      doc.text(String(v), 75, y);
      y += 7;
    });
    y += 4;
    doc.setFont("helvetica", "italic");
    const summaryLines = doc.splitTextToSize(reportData.executive.summary, 182);
    doc.text(summaryLines, 14, y);
    y += summaryLines.length * 5 + 8;
  }

  if (sectionOn(reportData, "systemInventory") && reportData.inventory) {
    doc.addPage();
    addPageHeader(doc, docTitle);
    y = 28;
    doc.setTextColor(...NAVY);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("System Inventory", 14, y);
    y += 10;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);

    const inv = reportData.inventory;
    const invSections = [
      ["System", [inv.system?.hostname, inv.system?.os, inv.system?.kernel].filter(Boolean).join(" · ")],
      [
        "CPU",
        [inv.cpu?.model, inv.cpu?.vendor, inv.cpu?.architecture,
          inv.cpu?.physical_cores != null ? `${inv.cpu.physical_cores} cores` : null].filter(Boolean).join(" · "),
      ],
      ["Memory", inv.memory?.dimm_count != null ? `${inv.memory.dimm_count} DIMM(s) installed` : "Not Available"],
      ["Storage", (inv.disks || []).map((d) => `${d.device}: ${d.model}`).join("; ") || "Not Available"],
      ["GPU", (inv.gpus || []).map((g) => `${g.vendor} ${g.model}`).join("; ") || "Not Available"],
      ["Network", (inv.nics || []).map((n) => n.name).join(", ") || "Not Available"],
      ["IO Devices", `${inv.io?.pci_count ?? 0} PCI · ${inv.io?.usb_count ?? 0} USB`],
    ];
    invSections.forEach(([label, value]) => {
      y = ensureSpace(doc, y, 12, docTitle);
      doc.setFont("helvetica", "bold");
      doc.text(`${label}:`, 14, y);
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(String(value), 150);
      doc.text(lines, 40, y);
      y += Math.max(lines.length * 4.5, 7) + 2;
    });
  }

  const componentSections = {
    CPU: "cpuAnalysis",
    GPU: "gpuAnalysis",
    RAM: "memoryAnalysis",
    DISK: "storageAnalysis",
    NIC: "networkAnalysis",
    "IO Control": "hardwareHealthOverview",
  };

  const compsToRender = reportData.componentAnalysis.filter((comp) => {
    const sid = componentSections[comp.name];
    return sid ? sectionOn(reportData, sid) : sectionOn(reportData, "hardwareHealthOverview");
  });

  if (compsToRender.length > 0) {
    doc.addPage();
    addPageHeader(doc, docTitle);
    y = 28;
    doc.setTextColor(...NAVY);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Component Health Analysis", 14, y);
    y += 10;

    compsToRender.forEach((comp) => {
      y = ensureSpace(doc, y, 30, docTitle);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...levelColor(comp.level));
      doc.text(`${comp.name} — ${statusLabel(comp.level)}`, 14, y);
      y += 6;
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);
      const statusLines = doc.splitTextToSize(comp.status, 182);
      doc.text(statusLines, 14, y);
      y += statusLines.length * 4 + 3;

      if (comp.inventory.length > 0) {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...GRAY);
        doc.text("Inventory:", 14, y);
        y += 5;
        doc.setFont("helvetica", "normal");
        doc.setTextColor(40, 40, 40);
        comp.inventory.slice(0, 3).forEach((line) => {
          doc.text(`• ${line}`, 18, y);
          y += 4.5;
        });
      }
      if (comp.liveMetrics.length > 0) {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...GRAY);
        doc.text("Live Metrics:", 14, y);
        y += 5;
        doc.setFont("helvetica", "normal");
        comp.liveMetrics.slice(0, 4).forEach(([k, v]) => {
          doc.text(`• ${k}: ${v}`, 18, y);
          y += 4.5;
        });
      }
      if (sectionOn(reportData, "activeFaults") && comp.faults.length > 0) {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...RED);
        doc.text(`Active Faults (${comp.faults.length}):`, 14, y);
        y += 5;
        doc.setFont("helvetica", "normal");
        doc.setTextColor(40, 40, 40);
        comp.faults.slice(0, 3).forEach((f) => {
          const line = f.metricName
            ? `${f.metricName}: ${f.currentValue || "—"} (threshold: ${f.thresholdCrossed || "—"})`
            : f.description || "—";
          doc.text(`• [${f.severity}] ${line}`, 18, y);
          y += 4.5;
        });
      }
      y += 4;
    });
  }

  if (sectionOn(reportData, "historicalTrends") && reportData.hardwareMetrics.length > 0) {
    doc.addPage();
    addPageHeader(doc, docTitle);
    y = 28;
    doc.setTextColor(...NAVY);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Hardware Metrics Summary", 14, y);
    y += 8;

    doc.setFillColor(...DARK);
    doc.rect(14, y, 182, 8, "F");
    doc.setTextColor(...WHITE);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    const cols = ["Metric", "Avg", "Min", "Max", "Current", "Trend"];
    const colX = [14, 62, 88, 114, 140, 166];
    cols.forEach((c, i) => doc.text(c, colX[i], y + 5.5));
    y += 10;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    reportData.hardwareMetrics.forEach((row, idx) => {
      y = ensureSpace(doc, y, 8, docTitle);
      if (idx % 2 === 0) {
        doc.setFillColor(245, 248, 252);
        doc.rect(14, y - 4, 182, 7, "F");
      }
      doc.setFontSize(8);
      row.forEach((cell, i) => doc.text(String(cell).slice(0, 22), colX[i], y));
      y += 7;
    });
  }

  if (sectionOn(reportData, "historicalTrends") && reportData.trendSeries.length > 0) {
    doc.addPage();
    addPageHeader(doc, docTitle);
    y = 28;
    doc.setTextColor(...NAVY);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Performance Trends", 14, y);
    y += 8;
    doc.setFontSize(9);
    doc.setTextColor(...GRAY);
    doc.text("Trend charts based on samples collected during this browser session.", 14, y);
    y += 10;

    reportData.trendSeries.forEach((series) => {
      y = ensureSpace(doc, y, 38, docTitle);
      doc.setTextColor(...NAVY);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text(series.label, 14, y);
      y += 5;
      drawLineChart(doc, series.points, 14, y, 182, 22);
      y += 30;
    });
  }

  if (
    sectionOn(reportData, "hardwareHealthOverview") &&
    (reportData.componentHealthSnapshot.length > 0 || reportData.faultDistribution)
  ) {
    doc.addPage();
    addPageHeader(doc, docTitle);
    y = 28;
    doc.setTextColor(...NAVY);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Health & Fault Charts", 14, y);
    y += 10;

    if (reportData.componentHealthSnapshot.length > 0) {
      doc.setFontSize(11);
      doc.text("Component Health Status", 14, y);
      y += 6;
      y = drawHorizontalHealthBar(doc, reportData.componentHealthSnapshot, 14, y, 182) + 8;
    }

    const sevItems = Object.entries(reportData.faultDistribution.bySeverity)
      .filter(([, v]) => v > 0)
      .map(([label, value]) => ({
        label,
        value,
        color: label === "Critical" ? RED : label === "Warning" ? ORANGE : GREEN,
      }));
    if (sevItems.length > 0) {
      y = ensureSpace(doc, y, 50, docTitle);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...NAVY);
      doc.text("Fault Distribution by Severity", 14, y);
      y += 8;
      drawBarChart(doc, sevItems, 14, y, 90, 30);
      y += 42;
    }
  }

  if (sectionOn(reportData, "connectivityStatus") && reportData.connectivityStatus) {
    doc.addPage();
    addPageHeader(doc, docTitle);
    y = 28;
    doc.setTextColor(...NAVY);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Connectivity Status", 14, y);
    y += 10;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    doc.text(`Overall Link Health: ${reportData.connectivityStatus.linkHealth?.overall || "—"}`, 14, y);
    y += 7;
    doc.text(`Health Score: ${reportData.connectivityStatus.linkHealth?.score ?? "—"}`, 14, y);
  }

  if (sectionOn(reportData, "faultTimeline") || sectionOn(reportData, "activeFaults")) {
    doc.addPage();
    addPageHeader(doc, docTitle);
    y = 28;
    doc.setTextColor(...NAVY);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Fault Analysis", 14, y);
    y += 10;

    if (reportData.faultAnalysis.length === 0) {
      doc.setFontSize(10);
      doc.setTextColor(...GRAY);
      doc.text("No faults or alerts logged during the selected interval.", 14, y);
    } else {
      reportData.faultAnalysis.forEach((fault) => {
        y = ensureSpace(doc, y, 24, docTitle);
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(
          fault.severity === "Critical" ? RED[0] : ORANGE[0],
          fault.severity === "Critical" ? RED[1] : ORANGE[1],
          fault.severity === "Critical" ? RED[2] : ORANGE[2]
        );
        const header = fault.metricName
          ? `[${fault.severity}] ${fault.component} — ${fault.metricName}`
          : `[${fault.severity}] ${fault.component}`;
        doc.text(header, 14, y);
        y += 5;
        doc.setFont("helvetica", "normal");
        doc.setTextColor(40, 40, 40);
        const explainLines = doc.splitTextToSize(fault.explanation, 182);
        doc.text(explainLines, 14, y);
        y += explainLines.length * 4 + 2;
        if (sectionOn(reportData, "faultTimeline")) {
          doc.setFontSize(7);
          doc.text(new Date(fault.t).toLocaleString(), 14, y);
          y += 6;
        }
        y += 4;
      });
    }
  }

  if (sectionOn(reportData, "recoveryHistory") && reportData.recoveryHistory?.length) {
    doc.addPage();
    addPageHeader(doc, docTitle);
    y = 28;
    doc.setTextColor(...NAVY);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Autonomous Recovery History", 14, y);
    y += 10;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    reportData.recoveryHistory.forEach((r) => {
      y = ensureSpace(doc, y, 12, docTitle);
      doc.text(
        `[${r.result}] ${r.component} — ${r.verificationOutcome || r.reason || ""} (${r.durationMs}ms)`,
        14,
        y
      );
      y += 6;
      doc.setFontSize(7);
      doc.text(r.timestamp, 14, y);
      y += 8;
      doc.setFontSize(9);
    });
  }

  if (sectionOn(reportData, "aiRootCause") && reportData.aiRootCause?.length) {
    doc.addPage();
    addPageHeader(doc, docTitle);
    y = 28;
    doc.setTextColor(...NAVY);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("AI Root Cause Analysis", 14, y);
    y += 10;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    reportData.aiRootCause.forEach((item) => {
      y = ensureSpace(doc, y, 14, docTitle);
      doc.setFont("helvetica", "bold");
      doc.text(`[${item.component}] ${item.severity}`, 14, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(item.analysis, 182);
      doc.text(lines, 14, y);
      y += lines.length * 4 + 6;
    });
  }

  if (sectionOn(reportData, "recommendations") && reportData.recommendations.length > 0) {
    doc.addPage();
    addPageHeader(doc, docTitle);
    y = 28;
    doc.setTextColor(...NAVY);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Recommendations & Corrective Actions", 14, y);
    y += 10;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    reportData.recommendations.forEach((rec, idx) => {
      y = ensureSpace(doc, y, 12, docTitle);
      const lines = doc.splitTextToSize(`${idx + 1}. ${rec}`, 182);
      doc.text(lines, 14, y);
      y += lines.length * 5 + 3;
    });
  }

  if (sectionOn(reportData, "rawTelemetry")) {
    doc.addPage();
    addPageHeader(doc, docTitle);
    y = 28;
    doc.setTextColor(...NAVY);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Appendix — Report Metadata", 14, y);
    y += 10;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    const meta = [
      ["Generated At", reportData.generatedAt.toISOString()],
      ["Report Interval", reportData.intervalLabel],
      ["Monitoring Start", reportData.span.start?.toLocaleString() || "Not Available"],
      ["Monitoring End", reportData.span.end?.toLocaleString() || "Not Available"],
      ["Sample Count", String(reportData.sampleCount)],
      ["CPU Model", reportData.context?.cpu_model || "Not Available"],
      ["GPU Model", reportData.context?.gpu_model || "Not Available"],
      ["Data Constraint", "All metrics sourced from live Hardware Monitor telemetry only"],
      ["Unsupported", "PSU, BMC, and Management telemetry are not collected by the backend"],
    ];
    meta.forEach(([k, v]) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${k}:`, 14, y);
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(String(v), 130);
      doc.text(lines, 55, y);
      y += Math.max(lines.length * 4.5, 7);
    });
  }

  const pageCount = doc.internal.getNumberOfPages();
  const stamp = reportData.generatedAt.toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const filename = `${sanitizeFilename(reportData.title)}_${stamp}.pdf`;
  const blob = doc.output("blob");

  return { blob, filename, pageCount, sizeBytes: blob.size, format: "pdf" };
}

/** Legacy helper — triggers immediate browser download */
export function downloadReportPdf(reportData) {
  const result = exportReportPdf(reportData);
  const url = URL.createObjectURL(result.blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = result.filename;
  a.click();
  URL.revokeObjectURL(url);
  return result.filename;
}
