/**
 * Recovery Action Catalog — keys MUST match CM.py RECOVERY_ACTIONS registry.
 * Frontend sends only action key + params; backend maps to Linux commands.
 */

export const RECOVERY_LEVEL_LABELS = {
  1: "Safe",
  2: "Confirmation Required",
  3: "High Risk",
};

/** @type {Array<object>} */
export const RECOVERY_ACTIONS = [
  {
    id: "cpu.renice",
    backendAction: "cpu.renice",
    level: 1,
    label: "Reduce Process Priority",
    impact: "Lowers scheduling priority via renice. Process continues running.",
    components: ["CPU"],
    requires: { process: true },
    defaultParams: { nice_value: 10 },
  },
  {
    id: "cpu.pause_process",
    backendAction: "cpu.pause_process",
    level: 2,
    label: "Pause Process",
    impact: "Sends SIGSTOP to suspend the process.",
    components: ["CPU"],
    requires: { process: true },
  },
  {
    id: "cpu.resume_process",
    backendAction: "cpu.resume_process",
    level: 1,
    label: "Resume Process",
    impact: "Sends SIGCONT to resume a paused process.",
    components: ["CPU"],
    requires: { process: true },
  },
  {
    id: "cpu.terminate_process",
    backendAction: "cpu.terminate_process",
    level: 3,
    label: "Terminate Process",
    impact: "Sends SIGTERM for graceful shutdown.",
    components: ["CPU"],
    requires: { process: true },
  },
  {
    id: "cpu.kill_process",
    backendAction: "cpu.kill_process",
    level: 3,
    label: "Force Kill Process",
    impact: "Sends SIGKILL. Unsaved work may be lost.",
    components: ["CPU"],
    requires: { process: true },
  },
  {
    id: "cpu.restart_service",
    backendAction: "cpu.restart_service",
    level: 2,
    label: "Restart Service",
    impact: "Restarts a systemd unit. Brief service interruption.",
    components: ["CPU"],
    requires: { service: true },
  },
  {
    id: "gpu.pause_process",
    backendAction: "gpu.pause_process",
    level: 2,
    label: "Pause GPU Process",
    impact: "Sends SIGSTOP to the GPU workload process.",
    components: ["GPU"],
    requires: { process: true },
  },
  {
    id: "gpu.resume_process",
    backendAction: "gpu.resume_process",
    level: 1,
    label: "Resume GPU Process",
    impact: "Sends SIGCONT to resume a paused GPU workload process.",
    components: ["GPU"],
    requires: { process: true },
  },
  {
    id: "gpu.terminate_process",
    backendAction: "gpu.terminate_process",
    level: 3,
    label: "Terminate GPU Process",
    impact: "Sends SIGTERM to the GPU workload process.",
    components: ["GPU"],
    requires: { process: true },
  },
  {
    id: "gpu.restart_persistence_daemon",
    backendAction: "gpu.restart_persistence_daemon",
    level: 2,
    label: "Restart nvidia-persistenced",
    impact: "Restarts the NVIDIA persistence daemon.",
    components: ["GPU"],
  },
  {
    id: "gpu.reset",
    backendAction: "gpu.reset",
    level: 3,
    label: "GPU Reset",
    impact: "Resets GPU via nvidia-smi. All GPU workloads interrupted.",
    components: ["GPU"],
    defaultParams: { gpu_id: "0" },
  },
  {
    id: "ram.drop_caches",
    backendAction: "ram.drop_caches",
    level: 2,
    label: "Drop Filesystem Cache",
    impact: "Drops page cache via /proc/sys/vm/drop_caches. Requires root.",
    components: ["RAM"],
  },
  {
    id: "ram.pause_process",
    backendAction: "ram.pause_process",
    level: 2,
    label: "Pause Memory Hog",
    impact: "Sends SIGSTOP to the top memory consumer.",
    components: ["RAM"],
    requires: { process: true },
  },
  {
    id: "ram.terminate_process",
    backendAction: "ram.terminate_process",
    level: 3,
    label: "Terminate Memory Hog",
    impact: "Sends SIGTERM to the top memory consumer.",
    components: ["RAM"],
    requires: { process: true },
  },
  {
    id: "ram.restart_service",
    backendAction: "ram.restart_service",
    level: 2,
    label: "Restart Service",
    impact: "Restarts a systemd service leaking memory.",
    components: ["RAM"],
    requires: { service: true },
  },
  {
    id: "disk.clean_temp_files",
    backendAction: "disk.clean_temp_files",
    level: 2,
    label: "Clean Temporary Files",
    impact: "Removes old files under /tmp and /var/tmp.",
    components: ["DISK"],
    defaultParams: { min_age_hours: 24 },
  },
  {
    id: "disk.vacuum_journal",
    backendAction: "disk.vacuum_journal",
    level: 2,
    label: "Vacuum System Journal",
    impact: "Shrinks systemd journal to reclaim disk space.",
    components: ["DISK"],
    defaultParams: { max_size: "500M" },
  },
  {
    id: "disk.identify_large_directories",
    backendAction: "disk.identify_large_directories",
    level: 1,
    label: "Identify Large Directories",
    impact: "Read-only du scan of directory sizes.",
    components: ["DISK"],
    defaultParams: { path: "/" },
  },
  {
    id: "disk.pause_process",
    backendAction: "disk.pause_process",
    level: 2,
    label: "Pause Disk I/O Process",
    impact: "Sends SIGSTOP to suspend the selected process.",
    components: ["DISK"],
    requires: { process: true },
  },
  {
    id: "disk.resume_process",
    backendAction: "disk.resume_process",
    level: 1,
    label: "Resume Disk I/O Process",
    impact: "Sends SIGCONT to resume a paused process.",
    components: ["DISK"],
    requires: { process: true },
  },
  {
    id: "disk.terminate_process",
    backendAction: "disk.terminate_process",
    level: 3,
    label: "Terminate Disk I/O Process",
    impact: "Sends SIGTERM for graceful process shutdown.",
    components: ["DISK"],
    requires: { process: true },
  },
  {
    id: "nic.restart_interface",
    backendAction: "nic.restart_interface",
    level: 2,
    label: "Restart Network Interface",
    impact: "Brings interface down then up via ip link.",
    components: ["NIC"],
    requires: { interface: true },
  },
  {
    id: "nic.renew_dhcp",
    backendAction: "nic.renew_dhcp",
    level: 2,
    label: "Renew DHCP Lease",
    impact: "Releases and renews DHCP via dhclient.",
    components: ["NIC"],
    requires: { interface: true },
  },
  {
    id: "nic.restart_network_manager",
    backendAction: "nic.restart_network_manager",
    level: 2,
    label: "Restart NetworkManager",
    impact: "Restarts NetworkManager service.",
    components: ["NIC"],
  },
  {
    id: "nic.reload_driver",
    backendAction: "nic.reload_driver",
    level: 3,
    label: "Reload NIC Driver",
    impact: "Unloads and reloads the NIC kernel module.",
    components: ["NIC"],
    requires: { interface: true },
  },
  {
    id: "nic.pause_process",
    backendAction: "nic.pause_process",
    level: 2,
    label: "Pause Process",
    impact: "Sends SIGSTOP to suspend the selected process.",
    components: ["NIC"],
    requires: { process: true },
  },
  {
    id: "nic.resume_process",
    backendAction: "nic.resume_process",
    level: 1,
    label: "Resume Process",
    impact: "Sends SIGCONT to resume a paused process.",
    components: ["NIC"],
    requires: { process: true },
  },
  {
    id: "nic.terminate_process",
    backendAction: "nic.terminate_process",
    level: 3,
    label: "Terminate Process",
    impact: "Sends SIGTERM for graceful shutdown.",
    components: ["NIC"],
    requires: { process: true },
  },
  {
    id: "pcie.rescan",
    backendAction: "pcie.rescan",
    level: 3,
    label: "PCI Bus Rescan",
    impact: "Triggers full PCI bus rescan. Requires root.",
    components: ["IO Control", "GPU"],
  },
  {
    id: "pcie.reload_driver",
    backendAction: "pcie.reload_driver",
    level: 3,
    label: "Reload PCIe Driver",
    impact: "Unbinds and rebinds driver for a PCI slot.",
    components: ["IO Control"],
    requires: { slot: true },
  },
];

const actionById = Object.fromEntries(RECOVERY_ACTIONS.map((a) => [a.id, a]));

export function getActionById(id) {
  return actionById[id] || null;
}

export function getActionByBackendKey(key) {
  return RECOVERY_ACTIONS.find((a) => a.backendAction === key) || null;
}
